[project]
name = "tennis"
version = "0.1.0"
description = "网球机器人的树莓派端程序"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "opencv-python>=4.8.0",
    "numpy>=1.24.0",
    "onnxruntime>=1.16.0",
    "Pillow>=10.0.0"
]
